feat: add error anotation

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -22,6 +22,15 @@ jobs:
       - name: Check coding style
         run: |
           check.sh $(pwd) $(pwd)
+          if [ -f coding-style-reports.log ]; then
+            while read -r line; do
+              file=$(echo "$line" | cut -d ':' -f 1)
+              line_number=$(echo "$line" | cut -d ':' -f 2)
+              error_message=$(echo "$line" | cut -d ':' -f 3-)
+              echo "::error file=$file,line=$line_number:: $error_message"
+            done < coding-style-reports.log
+            exit 1
+          fi
 
   push_to_mirror:
     if: github.event_name == 'push'
